# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helpDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_help(object):
    def setupUi(self, help):
        help.setObjectName("help")
        help.resize(428, 478)
        self.label = QtWidgets.QLabel(help)
        self.label.setGeometry(QtCore.QRect(10, 10, 411, 411))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(help)
        QtCore.QMetaObject.connectSlotsByName(help)

    def retranslateUi(self, help):
        _translate = QtCore.QCoreApplication.translate
        help.setWindowTitle(_translate("help", "Dialog"))
        self.label.setText(_translate("help", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt;\">A sample session file has been provided along with tool. </span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Click on</span><span style=\" font-size:10pt; font-weight:600;\"> Help-&gt;Sample Session Plan</span><span style=\" font-size:10pt;\"> file to open the file</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Create a session plan file according to the sample file</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Enter your username and password</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Select the LTPS structure</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Click on Browse button and open the session plan file created using the sample file</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Select the starting session from where you want to upload the session plan</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Click on Run open up the login window of ERP</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Username and Password will be entered automatically</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Enter the captcha and click login</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">Next, sit back, relax and see the magic happening...!</span></p><p align=\"justify\"><span style=\" font-size:10pt;\">The tool automatically generates a log file in the same folder </span></p><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">If you have any issues please mail the log file, along with a brief summary of the issue to avinash.s@klh.edu.in</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    help = QtWidgets.QDialog()
    ui = Ui_help()
    ui.setupUi(help)
    help.show()
    sys.exit(app.exec_())
